# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    container_name: lab8_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: lab8
    ports:
    - "5436:5432"

#docker-compose up -d
#docker-compose down
#